#%RAML 1.0 
title: To get all transaction for an account with status as pending
version: v1
protocols: [HTTPS]
baseUri: https://mocksvc.mulesoft.com/mocks/671355dc-2f30-4b0c-bd47-0cdf114d3148/api/v1/dda # baseUri: /api/v1/dda
mediaType: application/json
uses: 
  library: entityApi.raml
securitySchemes: 
  oauth2_0: !include transactionSecurityScheme.raml

/account/{accountId}/transaction/{status}:
 securedBy: oauth2_0
 get:      
  responses: 
    200:
     body: 
       application/json:
        type: library.Transaction
        example: 
         {
          "accountId":"10001",
          "transactionId":"111222333"
        }
         
        
  
    400:
     body: 
       application/json:
        type: library.Error
        example:
         { 
            "code" : "400",
            "message" : "Invalid Parameters",  
          }

    401:
     body: 
       application/json:
        type: library.Error
        example:
         {
            "code" : "401",
           "message" : "You are not authorized"  
         } 
    404:
     body: 
       application/json:
         type: library.Error 
         example: 
          { 
            "code" : "404",
            "message" : "Account Not found" 
          }

    405:
     body: 
       application/json:
         type: library.Error
         example:
          {
            "code" : "405",
           "message" : "Method Not Allowed"
           
         }
          
          