#%RAML 1.0 NamedExample
value: {
  
     "Transaction":
     
      {
      "accountId":"10001",
      "transactionId":"111222333",
    
      "transactionType":"WITHDRAWAL",
      "payee":"Jhon",
      "checkNumber":"556325",
      "status":"PENDING",
      "amount":5050
      }
     
 }

  